name: ci-test

on: 
  pull_request: 
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: check repository
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: './go.mod'

    # List go version
    - name: List version
      run: go version

    # Run build of the application
    - name: Run build
      run: make build 

    # Format code base to meet `go fmt` standard.
    - name: Format code
      run: make format

    # Run vet (this runs as part of go test too - could be removed)
    - name: Run vet
      run: go vet ./...
      
    # Run testing on the code
    - name: Run tests
      run: make test

    - name: Run code coverage
      env:
        MINIMUM_THRESHOLD: 80.00
      run: |
        echo "Code coverage check. Ensure code coverage is above $MINIMUM_THRESHOLD %"
        current=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'` 
        echo "Current test coverage is $current %"
        if (( $(echo "$current $MINIMUM_THRESHOLD" | awk '{print ($1 > $2)}') )); then
          echo "[PASSED] Code coverage above threshold."
        else
          echo "[FAILED] Code coverage below threshold."
        fi

